### ISSUE TITLE
Difficulty bar not updated

### ISSUE THREAD

**Issue by frankkoch** [frankkoch/moodle-mod_studentquiz#156]
Under Moodle prior to v3.7:
1) create a question
2) run as quiz and provide wrong answer for this question. As expected, you get a difficulty bar with 'my difficulty' = 100%
3) run the quiz again. This time provide a correct answer for the same question. Since now there is 1 correct and 1 incorrect answer, 'my difficulty' should be updated to 50%, but it ramains on 100%.

This error doesn't appear under Moodle v3.7

**Comment by HuongNV13** [comment]
This issue does not relate to any Moodle version

The issue come from the query to calculate difficulty bar that works normally with MySQL but return the wrong data with PostgreSQL (because **correctattempts** and **attempts** columns are in **Integer** type
d)

![image](https://user-images.githubusercontent.com/11548406/63498227-a7071d80-c4ef-11e9-9005-e0ae9aaed465.png)

Refer: https://www.postgresql.org/docs/8.0/functions-math.html

**division (integer division truncates results)**
