### ISSUE TITLE
Student Quiz creates quizzes in orphaned section 999 but moodle 3.3 has no orphaned sections

### ISSUE THREAD

**Issue by reactor0138** [frankkoch/moodle-mod_studentquiz#19]
Hi Frank
I see every time students create a quiz. Student quiz creates a copy of this quiz in the orphaned section 999. I suspect this is in order to capture the ratings and comments per question and perhaps to aid filters. 

- What happens if we delete these created quizzes. Do we lose data? What are these quizzes for?

- Moodle 3.3 has got rid of orphaned sections. How will student quiz cope with this?

**Comment by frankkoch** [comment]
Thank you for raising this issue. 

**What happens if we delete these created quizzes. Do we lose data? What are these quizzes for?**
SQ stores played quizzes in the orphaned section 999 in order to make them accessible for replay. This is not to store ratings or comments. Thus, if you delete some of these quizzes or even the entire section 999 you're losing the replay option only.

**Moodle 3.3 has got rid of orphaned sections. How will student quiz cope with this?**
 I just tested the new 2.0.3 release of StudentQuiz on Moodle 3.3. and it seems to be ok. The  orphaned section 999 is now renamed "studentquiz quizzes", but functionality seems to be the same. I will do further testing with a larger question bank.
