### ISSUE TITLE
Tags not visible when questions are in a subcategory

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#195]
Hello,
with the most recent StudentQuiz v4.1.1 2020013000 the tags in questions created by students are no longer visible in the StudentQuiz main question page if the question happens to be in a subcategory of the StudentQuiz.

However, when the question is moved from a subcategory to the main StudentQuiz category, tags are visible again. Maybe this is the purpose ?

**Comment by miroi** [comment]
When looking into this issue, I see that the questions some students are creating are showing up in one of the StudentQuiz subcategories.

I created these subcategories in StudentQuiz because I need them for moving tag-selected questions there before exporting questions in category for other Quizes.

**Comment by dionysius** [comment]
1)

> I see that the questions some students are creating are showing up in one of the StudentQuiz subcategories

![image](https://user-images.githubusercontent.com/1341084/74946102-160af380-53f9-11ea-8843-d08c0f92352c.png)
Yes, the create question page is actually just the question bank create question page, so all features there, including offering all subcategories, are available.
I think not much we can do about it. We send already the correct category in the url (`&category=...`) so the right category is pre selected, but we can't prevent the user from changing the category. The display and the save process are completely outside of StudentQuiz.

The only thing StudentQuiz offers is an own so-called 'context' which the question bank also obeys (In a context are e.g. permissions set, this is why - in short - students are allowed to create questions at all, since they create questions in the context of that exact StudentQuiz activity).


2)

> tags in questions created by students are no longer visible in the StudentQuiz main question page if the question happens to be in a subcategory of the StudentQuiz

I can confirm that so far. Additional note: Students can't move the question/change the category after they created it there.
