### ISSUE TITLE
Additional pages not visible if approval of questions is required

### ISSUE THREAD

**Issue by richardhaas** [frankkoch/moodle-mod_studentquiz#201]
We encountered an issue with a StudentQuiz with question approval required. New, unapproved questions filled the first page of the question list. Now students were unable to see any questions, even though there were multiple pages of approved and visible questions. Even the navigation bar for question pages was gone. The problem can be hotfixed by having at least one approved question on the first page, but this behaviour does not seem to be intended. Is it possible to pre-sort the list by visible and invisible items and put the visible ones in front?

**Comment by dionysius** [comment]
I can confirm this behaviour

As a teacher/admin:
![Screenshot from 2020-02-20 14 54 11](https://user-images.githubusercontent.com/1341084/74939620-82cdc000-53f0-11ea-8163-d691e5760022.png)
(All questions are new and hidden, questions are all from admin/teacher)

As a student:
![Screenshot from 2020-02-20 14 55 33](https://user-images.githubusercontent.com/1341084/74939697-a264e880-53f0-11ea-9bdd-f65b34938191.png)
(He can't see anything since all questions are hidden and none from him)

So, said student now creates a question, after that:
![Screenshot from 2020-02-20 14 58 52](https://user-images.githubusercontent.com/1341084/74939935-fec80800-53f0-11ea-9499-fa0e2fbaa623.png)
(He now can see his questions)

But as OP pointed out correctly, if the first page consists only of hidden questions, all the navigation is not displayed. In the following screenshot, the same thing happens when I was actually going to the second page:
![Screenshot from 2020-02-20 15 04 58](https://user-images.githubusercontent.com/1341084/74940484-c70d9000-53f1-11ea-96f7-adecdfb4587e.png)

So the issue here is: we don't correctly filter the question list. We actually should filter by visibility in the query itself, or the result, instead of just hiding it client side.

Because of this I'm sure this results in also that behavior: If page 1 and page 2 have only one question the student can see, they get 2 page navigation offered and each only having one question.
