### ISSUE TITLE
Last attempt in adaptive mode

### ISSUE THREAD

**Issue by cosminsabo** [frankkoch/moodle-mod_studentquiz#213]
Hello,

I use the StudentQuiz module, which allows students to use a mechanism for synthesizing knowledge through questions in a competitive and social environment. I love this module.

However, when trying to use the CodeRunner module in which questions are run in adaptive mode (as they provide immediate feedback), the last answer to the question is always marked as always wrong.

I attach an image that indicates this behavior.
![2020-03-31_9-17-01](https://user-images.githubusercontent.com/9219580/78014444-9dc91380-7350-11ea-91b7-f5d90e8928ec.png)

Thank you for your support!

**Comment by dionysius** [comment]
Hmm... I tried it out...

![Screenshot from 2020-04-26 19 16 59](https://user-images.githubusercontent.com/1341084/80314896-a8ae8100-87f4-11ea-92cf-afdd3bf887f2.png)

Even if the question got correctly anwered on the first attempt (so the Marks are 1.00 included with previous tries).

From the internals of StudentQuiz: Anything that is not exactly graded 'right' is wrong, so partially right etc. will all be read as wrong.

Needs a bigger dive into what is written to the db and interpreted from it. While we offer support for additional question types due to the fact we're using the moodle core code to go through the question and display it, we never tested outside of the moodle standard question types. (That's all I got for today)

Do you use question type plugins which work/don't work? (and are easier/smaller to look into?)

**Comment by timhunt** [comment]
Very odd. I would look at the output of a version of this query https://docs.moodle.org/dev/Overview_of_the_Moodle_question_engine#Detailed_data_about_an_attempt, to see how the student's interaction withe the question is recorded in the database.

**Comment by timhunt** [comment]
Right, that is interesting, and not necessarily what I was expecting:

![image](https://user-images.githubusercontent.com/138653/80350894-4fcd0000-8869-11ea-85e1-725a5a7f23b4.png)

This is an incompatibility between StudentQuiz (which wants question to always use immediate feedback behaviour) and CodeRunner (which insists on always using Adaptive behviour). And, one feature of adaptive behaviour is that it never finishes during the attempt.

This incompatibility could be resolved at either end:

1. the first option might be this propose change to adaptive behaviour MDL-65825 - which might make it 'finish' (change state from completed to gradedright when the student gets to 100%). No, actually, this goes against the philosopy of Adaptive behaviour.
2. The second option is to handle this in StudentQuiz. ... And I can see there is already some support for this, based on the $canfinish variable in attempt.php. ... in fact, this code is already present, just with one small omission:

https://github.com/frankkoch/moodle-mod_studentquiz/blob/5bc3f08ac5cf8e96c2018b7cf78cfe32c14f4554/attempt.php#L90 is the right thing to do (Except, it might be best to only do it if the question is not already finished). However, it won't have any effect, unless you call save_questions_usage_by_activity!

OK, pull request coming up.

**Comment by timhunt** [comment]
Well, unfortunately, this change https://github.com/timhunt/moodle-mod_studentquiz/commit/adaptive-partial-fix is not enougn on its own. With that change the coderunner question does end up in 'gradedright' state in the question usage, but clearly some StudentQuiz processing is then needed to update something else. So, I hope this is a useful hint, but someone who knows more about StudentQuiz will need to take it from here.

**Comment by dionysius** [comment]
Thank you @timhunt. I think I can take over from here
