### ISSUE TITLE
Not work with RECORD AUDIO question type

### ISSUE THREAD

**Issue by bird2019** [frankkoch/moodle-mod_studentquiz#259]
Not working properly with "Record audio" question type. there are no buttons showing for submint, ranking, comments, the same story on adaptable and boost themes. Is this a bug? I am on 3.9.1.
![studentquiz](https://user-images.githubusercontent.com/46427226/89798514-8e42ae00-db2c-11ea-88c0-3daa74257551.JPG)

**Comment by bird2019** [comment]
Envirenment: Moodle 3.9.1  php7.2.33   mariadb10.4.13

**Comment by timhunt** [comment]
It looks like StudentQuiz has special logic to handle Essay questions (https://github.com/frankkoch/moodle-mod_studentquiz/blob/aedbde18ef2b7819ecd117242de9a072e07ce540/attempt.php#L180 and https://github.com/frankkoch/moodle-mod_studentquiz/blob/2b051d8914fc5b3a64befe57e80c13ac01fa8a80/locallib.php#L985).

However, really, it should not be coded like that. Rather than specifically codeing the logic for one question type, it should be done generically, using $canfinish in attempt.php $qtype->is_manual_graded() in mod_studentquiz_get_question_types.

**Comment by dionysius** [comment]
I will look into question types as the next big batch. Keep the types coming which don't work (like #213) so I have a good range of question types to test with.

**Comment by dionysius** [comment]
I finally had the chance to look into the adaptive questions and got the PR up so I can look into this issue now.

While @timhunt is right, that his linked parts could be done better, the issue still exists: How is StudentQuiz supposed to handle question types which require *manual grading*. StudentQuiz relies on question types to grade the questions automatically after an answer has been provided.

I can remove the exclusions for "essay" and other similiar question types, but I still don't know how StudentQuiz should handle the answer result. Is such question answer always right or always wrong?

**Comment by dionysius** [comment]
With the latest discussion in https://github.com/frankkoch/moodle-mod_studentquiz/pull/286#issuecomment-722664174, question types which are not gradeable automatically are excluded.

To remove unusable question types in the "Create question" selection open your StudentQuiz settings page and save it again. This will save the custom defined allowed question types list without the invalid question types.
