### ISSUE TITLE
Full MariaDB support

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#26]
Currently MariaDB doesn't behave like MySQL on the dashboard page. It always returns no questions and thus renders the question table as empty, even if there are questions.

We're working hard to find the cause. Everything else is working on MariaDB.

If you want to help to track it down, attached the minimal not working example:
- db export
- problematic query
- screenshots about results mariadb vs mysql

You only need a fresh database to try it out. At best we'd like to fix the query so it works on both.

[studentquiz_mariadb_issue_mnwe.zip](https://github.com/frankkoch/moodle-mod_studentquiz/files/1635184/studentquiz_mariadb_issue_mnwe.zip)

**Comment by RoHaX** [comment]
Hi, 
I installed StudentQuiz today and couldnt get it to work. After some research i found the Problem with mariaDB here. I tried to debug your SQL Statement and here is my result - maybe it will help you to find the Problem.

First i had some troubles with the Dump. Columns 'name' and 'stamp' where to short so i had emty tables:

INSERT INTO `mdl_question_categories` VALUES (1,'Default for StudentQuiz 1',29,'The default category for questions shared in context \'\'.',0,'server.edu.hsr.ch+171208133345+zWXrRI',2,999),(2,'Default for Course One',21,'The default category for questions shared in context \'Course One\'.',0,'server.edu.hsr.ch+171208133346+wrhuIE',0,999),(3,'Default for StudentQuiz 2',30,'The default category for questions shared in context \'\'.',0,'server.edu.hsr.ch+171208133412+fQGYcq',2,999),(4,'Default for Miscellaneous',3,'The default category for questions shared in context \'Miscellaneous\'.',0,'localhost+180115144132+aCtpRL',0,999),(5,'Default for System',1,'The default category for questions shared in context \'System\'.',0,'localhost+180115144132+51F8tn',0,999);
ERROR 1406 (22001): Data too long for column 'name' at row 1


MariaDB [mdltest]> INSERT INTO `mdl_question_categories` VALUES (1,'Default for StudentQuiz 1',29,'The default category for questions shared in context \'\'.',0,'server.edu.hsr.ch+171208133345+zWXrRI',2,999),(2,'Default for Course One',21,'The default category for questions shared in context \'Course One\'.',0,'server.edu.hsr.ch+171208133346+wrhuIE',0,999),(3,'Default for StudentQuiz 2',30,'The default category for questions shared in context \'\'.',0,'server.edu.hsr.ch+171208133412+fQGYcq',2,999),(4,'Default for Miscellaneous',3,'The default category for questions shared in context \'Miscellaneous\'.',0,'localhost+180115144132+aCtpRL',0,999),(5,'Default for System',1,'The default category for questions shared in context \'System\'.',0,'localhost+180115144132+51F8tn',0,999);
ERROR 1406 (22001): Data too long for column 'stamp' at row 1

I fixed it by increase varchar(20) to varchar(50)

I still got no result, then i found out a Problem here:

MariaDB [mdltest]> select * from mdl_question_attempt_step_data;
+----+---------------+---------+-------+
| id | attemptstepid | name    | value |
+----+---------------+---------+-------+
|  1 |             2 | -submit | 1     |
|  2 |             2 | answer  | 1     |
|  3 |             4 | -submit | 1     |
|  4 |             4 | answer  | 0     |
|  5 |             6 | -submit | 1     |
|  6 |             6 | answer  | 1     |
|  7 |             8 | -submit | 1     |
|  8 |             8 | answer  | 1     |
|  9 |            10 | -submit | 1     |
| 10 |            10 | answer  | 0     |
| 11 |            12 | -submit | 1     |
| 12 |            12 | answer  | 0     |
| 13 |            14 | -submit | 1     |
| 14 |            14 | answer  | 0     |
| 15 |            16 | -submit | 1     |
| 16 |            16 | answer  | 1     |
| 17 |            18 | -submit | 1     |
| 18 |            18 | answer  | 0     |
+----+---------------+---------+-------+
18 rows in set (0.00 sec)


MariaDB [mdltest]> SELECT Max(qasd.id)
    ->         FROM mdl_studentquiz sq
    ->         JOIN mdl_studentquiz_attempt sqa ON sqa.studentquizid = sq.id
    ->         JOIN mdl_question_usages qu ON qu.id = sqa.questionusageid
    ->         JOIN mdl_question_attempts qa ON qa.questionusageid = qu.id
    ->         LEFT JOIN mdl_question_attempt_steps qas ON qas.questionattemptid = qa.id
    ->         LEFT JOIN mdl_question_attempt_step_data qasd ON qasd.attemptstepid = qas.id
    ->         GROUP BY qa.questionid;
+--------------+
| Max(qasd.id) |
+--------------+
|            2 |
|           10 |
|           18 |
|           16 |
+--------------+
4 rows in set (0.00 sec)


MariaDB [mdltest]>  select * from mdl_question_attempt_step_data where name = '-submit';
+----+---------------+---------+-------+
| id | attemptstepid | name    | value |
+----+---------------+---------+-------+
|  1 |             2 | -submit | 1     |
|  3 |             4 | -submit | 1     |
|  5 |             6 | -submit | 1     |
|  7 |             8 | -submit | 1     |
|  9 |            10 | -submit | 1     |
| 11 |            12 | -submit | 1     |
| 13 |            14 | -submit | 1     |
| 15 |            16 | -submit | 1     |
| 17 |            18 | -submit | 1     |
+----+---------------+---------+-------+
9 rows in set (0.00 sec)



So that part could not work, because there is no Dataset with name= '-submit' and id IN (2,10,18,16):

This SQL-statement wont work:

SELECT qa.questionid
          qas.state mylastattempt
   FROM mdl_studentquiz sq
   JOIN mdl_studentquiz_attempt sqa ON sqa.studentquizid = sq.id
   JOIN mdl_question_usages qu ON qu.id = sqa.questionusageid
   JOIN mdl_question_attempts qa ON qa.questionusageid = qu.id
   LEFT JOIN mdl_question_attempt_steps qas ON qas.questionattemptid = qa.id
   LEFT JOIN mdl_question_attempt_step_data qasd ON qasd.attemptstepid = qas.id
   WHERE qasd.name = '-submit'
     AND qasd.id IN
       (SELECT Max(qasd.id)
        FROM mdl_studentquiz sq
        JOIN mdl_studentquiz_attempt sqa ON sqa.studentquizid = sq.id
        JOIN mdl_question_usages qu ON qu.id = sqa.questionusageid
        JOIN mdl_question_attempts qa ON qa.questionusageid = qu.id
        LEFT JOIN mdl_question_attempt_steps qas ON qas.questionattemptid = qa.id
        LEFT JOIN mdl_question_attempt_step_data qasd ON qasd.attemptstepid = qas.id
        GROUP BY qa.questionid)
		
I tried to change "AND qasd.id IN" to "AND qasd.attemptstepid IN" so i get a result:

SELECT qa.questionid
          qas.state mylastattempt
   FROM mdl_studentquiz sq
   JOIN mdl_studentquiz_attempt sqa ON sqa.studentquizid = sq.id
   JOIN mdl_question_usages qu ON qu.id = sqa.questionusageid
   JOIN mdl_question_attempts qa ON qa.questionusageid = qu.id
   LEFT JOIN mdl_question_attempt_steps qas ON qas.questionattemptid = qa.id
   LEFT JOIN mdl_question_attempt_step_data qasd ON qasd.attemptstepid = qas.id
   WHERE qasd.name = '-submit'
     AND qasd.attemptstepid IN
       (SELECT Max(qasd.id)
        FROM mdl_studentquiz sq
        JOIN mdl_studentquiz_attempt sqa ON sqa.studentquizid = sq.id
        JOIN mdl_question_usages qu ON qu.id = sqa.questionusageid
        JOIN mdl_question_attempts qa ON qa.questionusageid = qu.id
        LEFT JOIN mdl_question_attempt_steps qas ON qas.questionattemptid = qa.id
        LEFT JOIN mdl_question_attempt_step_data qasd ON qasd.attemptstepid = qas.id
        GROUP BY qa.questionid)
				
Maybe a hint? Im not very good in SQL but i hop it helps to fix it for mariaDB - i can Test if you tell me in which PHP to change something.

**Comment by dionysius** [comment]
There's a good chance I find time this weekend to look into it.

In the meantime I can offer a dirty workaround: https://github.com/frankkoch/moodle-mod_studentquiz/archive/dirty-mariadb-workaround.zip

In the branch dirty-mariadb-workaround (based on v3.0.1) I've removed the problematic part of the query, but this produces another bug: In the field "my last attempt" in the question table of the overview page will always stay "n.a.". The rest of StudentQuiz is not affected. This makes this plugin at least usable and that bug doesn't "hurt" that much.

**Comment by dionysius** [comment]
So, I tried to remove as much bloat as possible from the query, I have now a almost understandable query. This query doesn't represent now what it should do, it is here to find out what technical reason there is for the different results.

``` mysql
SELECT    q.id, 
          q.qtype, 
          q.name,
          mylatts.mylastattempt
FROM      mdl_question q 
LEFT JOIN ( 
                    SELECT    qa.questionid, 
                              qas.state mylastattempt 
                    FROM      mdl_question_attempts qa
                    LEFT JOIN mdl_question_attempt_steps qas ON qas.questionattemptid = qa.id 
                    LEFT JOIN mdl_question_attempt_step_data qasd ON qasd.attemptstepid = qas.id 
                    WHERE     1
                    AND       qasd.id IN 
                              ( 
                                        SELECT    Max( subqa.id ) 
                                        FROM      mdl_question_attempts subqa
                                        WHERE     1
                              )
) mylatts ON mylatts.questionid = q.id
```

MariaDB:
```
Result:
id |qtype     |name |mylastattempt |
---|----------|-----|--------------|
2  |truefalse |Q1   |gradedwrong   |

```

MySQL:
```
Result:
id |qtype     |name    |mylastattempt |
---|----------|--------|--------------|
1  |truefalse |Frage 2 |              |
2  |truefalse |Q1      |gradedwrong   |
3  |truefalse |Frage 4 |              |
4  |truefalse |Frage 3 |              |
```

**Comment by dionysius** [comment]
@frankkoch @RoHaX In my short manual tests I couldn't find any issues with mariadb and also no regression issues on mysql and postgres. We might be able to release the fix.

I'd like to include the pull request https://github.com/frankkoch/moodle-mod_studentquiz/pull/38 into the release, so hopefully we can do it soon

**Comment by RoHaX** [comment]
Great - i just testet and it works!

StudentQuiz is a great AddOn für Moodle - you did a great Job!
Thanks

**Comment by dionysius** [comment]
Unluckily there [seems to be no mariadb support in moodle-plugin-ci](https://github.com/moodlerooms/moodle-plugin-ci/issues/76#issuecomment-372471665), so for now, continuous tests to are not possible. But going to make a release today.
