### ISSUE TITLE
Does not work with Moodle Mobile App

### ISSUE THREAD

**Issue by wallyreport** [frankkoch/moodle-mod_studentquiz#264]
Maybe this is more of feature request? I cannot get this to work with Moodle Mobile App. Is there anything I can do?

**Comment by dionysius** [comment]
That's definitely what we always wanted. Whatever I write now might not be completely correct, as this has been a while we looked at that, but it should give you a little insight.

Unfortunately we ran into the problem, that the question library of Moodle is not versatile/available for other modules in the Mobile App. Very simplified: You have to think in the way that StudentQuiz is "just using" the questions in the exact way moodle offers, so for the Mobile compatibility there has to be a similiar way for us to "just use" those questions.

There are efforts at Moodle to address this issue with the possibility to integrate StudentQuiz as well into the Moodle core. But this has been postponed from time to time because it's a lot of effort making those requirements possible. But those changes would definitely help any plugin using questions in the Mobile App.

Isn't there an option to define the module as a "web" version? It's probably not looking great for mobile.
