### ISSUE TITLE
Any way to set "Page Length" permenately?

### ISSUE THREAD

**Issue by wallyreport** [frankkoch/moodle-mod_studentquiz#295]
I try to keep quizzes under 20 questions, but sometimes it cannot be helped.

If a learner goes to the StudentQuiz activity, and selects "Start Quiz" The quiz will go through the first 20 questions, and then it will appear the quiz is over.  This even if the questions on the next page are checked.

The learner needs to go back to the first page of the activity, then select the next page. This can be confusing to some. Some will think the quiz is simply over. This is unfair to the learner.

Is there any way I can set this so "Start Quiz" will through all the quiz questions?

I noticed that the "Page Length" can be set, but that sets back to 20 after one session.

**Comment by frankkoch** [comment]
Hi Wallyreport, try the filters to create your prefered set of questions instead of the select-boxes. There's no limit to the number of questions within a quiz.

To avoid the 20-limit due to pagination, you could also click on "show all". This will select all questions within the collection. You might end up with a very long quiz.

**Comment by wallyreport** [comment]
Maybe I have not been clear. 
Let's suppose I have 25 questions in the quiz. 
My concern is: a learner (not me) will go to the quiz, see all the boxes ticked, and and then click on the "Start Quiz" button. After 20 questions, the learner will think he/she is done, and end up ignoring the last 5 questions. If somebody is not familiar with the plugin, that person could easily miss the second page with the last 5 questions. As such, it would be very helpful if all the questions were on one page. 
Somebody unfamiliar with the plugin, would probably not know about setting the "page size" or anything like that. 
I am not sure where this "show all" setting is. But I need something that will permanently set the plugin so that when the learner clicks "Start Quiz" the learner will get all the quiz questions, instead of stopping at 20.

**Comment by frankkoch** [comment]
There are many quizzes out there with hundreds and even thousands of questions. It would take way too long to list all of them and a quiz of such size wouldn't be helpful either. Also, the StudentQuiz progress bar indicates to each student his or her progress through the collected questions. So your students can easily see if they're missing questions. Please let them know about the concept of paging and the "show all" possibility.

**Comment by wallyreport** [comment]
All I want is for the learner to get _**all**_ the questions before being presented with the "Finish" button. The questions do not have to be listed on one page. It is okay to have the questions on different pages, but when a learner clicks "Start Quiz" the quiz needs to continue through _**all**_ the questions. The quiz should not stop half-way through. That is confusing. I feel certain that learners, not familiar with the plugin, will think they have completed the quiz before the quiz is actually complete.

**Comment by dionysius** [comment]
I may add also my two cents:

The main goal of StudentQuiz is helping the student to learn effectively and collaboratively. It is not the goal to be the all in one quiz solution. Each student has different strengths and different interpretations on what he wants or needs to learn when taking the quiz and what he tries to teach or gives his view other students by his questions. **There will always be only a subset of the question which are viable to be taken**, often depending on the students weaknesses and strengths, and some questions on the same topic are just better than others. That's why the aim of StudentQuiz is providing a tool set to get to the good questions, a tool to get the questions fitting for that students aim and needs. This is effective in learning a topic, as the content to be learned is channelled and targeted as good as we could. Our name is program, the student is in the focus of the quiz.

The only thing i can offer to discuss about is renaming the button to: "Run quiz with selected questions".
