### ISSUE TITLE
Open discussion: Hidden questions do not count towards the ranking currently, should they?

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#297]
With the help of the community during the investigation on the issue #284 we discovered that hidden questions might not interact with the ranking as people expected. First resolution and thoughts starting from [this comment](https://github.com/frankkoch/moodle-mod_studentquiz/issues/284#issuecomment-732346791) until the end of the issue.

This means from the ranking point of view hidden questions are non-existent. This hidden-feature got introduced with the introduction of the question states 2 years ago, which happened after the initial model of the calculation for the ranking. Keep in mind, that there is also a personal progress block and a statistics page whose counting/calculation also differs.

Definition what a hidden question represents: A hidden question is a question a student has created, but is not visible by other students and no student can play this question in the quiz. Only the teacher is able to unhide or approve (with automatic unhide) this question and only then it is available for everyone in that StudentQuiz. A teacher can also hide a question later again.

Overall the open discussion is: What do you expect what a hidden question does mean? What do you think is also reasonable to be understood otherwise? What do hidden questions affect in the counting/calculation? Where would you draw the line of what or where it has an impact and what or where not? Is it just visual or is there a meaning behind it?

Currently, hidden questions are completely excluded from the ranking calculation. It might help to formulate your opinion on the questions above with the following questions, as these are usually the possible impacts the hidden questions could have in the ranking:

- If question creation factor is set and hidden questions would count there, the student can just boost his ranking by making many meaningless questions. Should this be tolerated? (The student might remove the questions again before ending of the class so the teacher couldn't notice)
- In a StudentQuiz without automatic publishing, should the student get points for a question that he just created and is hidden?
- Should a student get points for a question that is approved but hidden? (That question might got hidden by the teacher for just an organisational reason, not because the question was bad)
- Should a student get points for a created question which is disapproved but otherwise visible to others? (pointing to the conflict of the question created factor and approved question factor)
- Should there be a new factor for disapproved questions that can be set negative? (to make up the previous question - analog the factor for last wrong attempts if set to negative)
- Or has questions created factor missed it's point with the hidden questions now? (because one could see: a question is either approved, then it gets points, or not otherwise - independent in which state the question is)
- Should existing ratings on a hidden question (because it got hidden later) count towards the ranking? (That question might got hidden by the teacher for just an organisational reason, not because the question was bad)
- Should hidden questions of other students count towards the personal progress in the ranking table? (must be no, as he's never able to see that question, but still wanted to point that out)
- Do teachers know that hidden questions don't count anything towards the ranking? That it is currently more than just an organisational tool?
- Can we expect teachers and organisation using that feature for different reasons? Hidden might mean something different for different people.
  - Example: It could be "abused" to limit the visibility to only a specific set of questions the teacher has picked out using the students questions? Better way would be to copy those questions and make a quiz, but just to underline the creativity people have when they try to fit it in their lessons.

It got a bit long, don't find an answer for any question. Just let me know of your thoughts :)

cc @frankkoch @HuongNV13 @Peyje @lucaboesch @machiaveli88 @zabellemotte

**Comment by frankkoch** [comment]
Great discission, thank you for all the input. 

I agree withe the definition of hidden questions being treated like "non-existing". Thus, they should not be considered in the ranking table, nor in the progess bars, nor in the statistics. To state it differently, only visible questions should generate points for contribution _(points for each created question, points for each approved question, points for each star received)_ and for answering competence _(latest correct answer factor, latest wrong answer factor)_.

Even if a studend has already reveived points for a visible question _(either by creating it or by answering such a question)_, these points disappear as soon as the question is set to hidden. Otherwise, ranking table and progress bars would state calculations which cannot be verified due to the invisibility of questions.

In case of a StudentQuiz with "Question publishing" set to _'Require approval before publishing'_ a questions becomes visible only once it becomes approved, and just in this case it shows up in the ranking table, in the progess bars, and in the statistics.

**To summarize the possible combinations _(I am using the default point scheme)_:**


Automatic   publishing | State | Visibility |   | Points for each created question | Points for each approved question | Points for each star received
-- | -- | -- | -- | -- | -- | --
Yes | New | visible |   | 10 | 0 | 3
Yes | Approved | visible |   | 10 | 5 | 3
Yes | Disapproved | visible |   | 10 | 0 | 3
Yes | Changed | visible |   | 10 | 0 | 3
Yes | New | **hidden** |   | 0 | 0 | 0
Yes | Approved | **hidden** |   | 0 | 0 | 0
Yes | Disapproved | **hidden** |   | 0 | 0 | 0
Yes | Changed | **hidden** |   | 0 | 0 | 0
  |   |   |   |   |   |  
No | New | **hidden** |   | 0 | 0 | 0
No | Approved | visible |   | 10 | 5 | 3
No | Disapproved | **hidden** |   | 0 | 0 | 0
No | Changed | **hidden** |   | 0 | 0 | 0

Some more more points because the table above doesn't answer all questions:

_> Should there be a new factor for disapproved questions that can be set negative? (to make up the previous question - analog the factor for last wrong attempts if set to negative)_
No, otherwise students might become affraid to raise a question.

_> Or has questions created factor missed it's point with the hidden questions now? (because one could see: a question is either approved, then it gets points, or not otherwise - independent in which state the question is)_
_'Points for each created question'_ has not missed its point. Its an appreciation for contribution, no matter whether the question becomes approved or not. There are extra points for the approval _('Points for each approved question')_ and for the quality of the question _('Points for each star received')_. By the way, if 10 points for _'Points for each created question'_ don't seem appropriate, this value can be configured.

_>Should existing ratings on a hidden question (because it got hidden later) count towards the ranking? (That question might got hidden by the teacher for just an organisational reason, not because the question was bad)_
No, it shouldn't. Only visible questions count in the ranking table, in the progess bars, and in the statistics. Otherwise, these calculations cannot be verified due to the invisibility of questions.

_> Should hidden questions of other students count towards the personal progress in the ranking table? (must be no, as he's never able to see that question, but still wanted to point that out)_
I agree with 'No', however, the question might have been visible before. But even then, as long as its invisible, it does not generate any points anymore.

_> Do teachers know that hidden questions don't count anything towards the ranking? That it is currently more than just an organisational tool?_
Yes, it is documented at https://docs.moodle.org/310/en/StudentQuiz_module#Evaluation_from_the_teacher

_> Can we expect teachers and organisation using that feature for different reasons? Hidden might mean something different for different people._
I'm afraid we cannot address all possible forms of usage. The purpose of StudentQuiz is to empower students create and share their own question-pool. The teacher becomes a coach by providing feedback _(approval, disapproval, comments)_ and should use the power of _'hiding'_ only if something went very wrong, e.g. questions containing inappropriate content.

Best regards, Frank

**Comment by Peyje** [comment]
While I mostly agree with your points regarding hidden questions not being evaluated for calculation of points (especially in terms of transparency of how points are given out), I have to disagree with this part:
> Or has questions created factor missed it's point with the hidden questions now? (because one could see: a question is either approved, then it gets points, or not otherwise - independent in which state the question is)
>>'Points for each created question' has not missed its point. Its an appreciation for contribution, no matter whether the question becomes approved or not. There are extra points for the approval ('Points for each approved question') and for the quality of the question ('Points for each star received'). By the way, if 10 points for 'Points for each created question' don't seem appropriate, this value can be configured.

That might be true as long as questions are published automatically. But let's take a look at the other possibility, as you said yourself:
> In case of a StudentQuiz with "Question publishing" set to 'Require approval before publishing' a questions becomes visible only once it becomes approved, and just in this case it shows up in the ranking table, in the progess bars, and in the statistics.

This leads to the problem that a hidden (disapproved or just not yet approved - be it because of organizational or other reasons) question does not give the student the points for a created question, and therefore behaving differently to the "questions released automatically"-mode. So now, instead of getting points for just creating a question, you only get those if your question is approved, making the "created question"-points superfluous.

My proposed solution for this would be to disable the "created question"-points altogether for the "Require approval before publishing"-mode, leading to this table:

Automatic   publishing | State | Visibility |   | Points for each created question | Points for each approved question | Points for each star received
-- | -- | -- | -- | -- | -- | --
Yes | New | visible |   | 10 | 0 | 3
Yes | Approved | visible |   | 10 | 5 | 3
Yes | Disapproved | visible |   | 10 | 0 | 3
Yes | Changed | visible |   | 10 | 0 | 3
Yes | New | hidden |   | 0 | 0 | 0
Yes | Approved | hidden |   | 0 | 0 | 0
Yes | Disapproved | hidden |   | 0 | 0 | 0
Yes | Changed | hidden |   | 0 | 0 | 0
  |   |   |   |   |   |  
No | New | hidden |   | - | 0 | 0
No | Approved | visible |   | - | 5 | 3
No | Disapproved | hidden |   | - | 0 | 0
No | Changed | hidden |   | - | 0 | 0

With this, hidden questions do not count into the points and depending on the mode of how questions are released, a student either
_gets points for creating a question and then again if this question is approved_
or
_gets points for a question that is published._

**Comment by frankkoch** [comment]
I agree that in case of 'Require approval before publishing' it doesn't make much sense to distinguish between "points for each question created" and "points for each question approved" because both are gained by the same approval-action. However, if once we operate with "points for each question created" and once without, StudentQuiz becomes more difficult to understand. This different behaviour also has to be implemented and documented. And if somebody doesn't like 15 points instead of 5, he/she could just set "points for each question created" to 0 and gets the same effect.

**Comment by Peyje** [comment]
That would make it more difficult, true. How about renaming "Points for **creating** a question" to "Points for a **published** question"? 
This would maybe fit better to the current visibility of the question, as a created yet hidden question does not grant points.
Also, that would make the behavior in the case of "Require approval before publishing" more clear.

**Comment by frankkoch** [comment]
This sounds like a great compromise :-) Thank you for your creativity.

**Comment by dionysius** [comment]
I also like this suggestion. Publish is basically the opposite of hidden. It matches also with the already existing description for the publishing setting: https://github.com/frankkoch/moodle-mod_studentquiz/blob/fix_284/lang/en/studentquiz.php#L446

> Published questions appear in the question pool for other students to take them.

That implies that only publish questions can be taken and this implies only those are relevant for the ranking.
