### ISSUE TITLE
access question edit tab

### ISSUE THREAD

**Issue by rschrenk** [frankkoch/moodle-mod_studentquiz#304]
Hi,

we suffer from the problem `Sorry, but you do not currently have permissions to do that (access question edit tab questions)` as also described in #270 and #203. It "randomly" appears for some users, but not for others, although all permissions and capabilities are exactly the same.

As far as I understood the problem in the other issues, the permissions are overwritten after a role_assigned or role_unassigned event occurs, but Moodle uses the cache for those assignments. Our system uses multiple webhosts and we have split the cache by using sticky sessions on our proxy. So every webnode must update its cache itself. As a consequence it would be necessary to purge the caches on all webnodes every time a user has changed any role in a course that has a studentquiz, which is impossible to do.

Do you have any idea how we can handle this situation?

Kind regards

**Comment by dionysius** [comment]
While replying on your other issue #306 this got me thinking: Did you modify already the event implementation of studentquiz before raising this issue? Because if you remove one of those, you've removed the case where it should apply those changes and thus it sounds reasonable that you hit the case for missing permissions. Just a bold assumption, can be untrue.

The caching iself *is* a problem where we don't know where it comes from, the tracking of this issue is #203. Any input and idea is valuable. Right now I can say, that StudentQuiz is correctly using the libs provided by Moodle for updating capabilities and roles, and those functions do also handle the invalidation of those cache elements. It is right now out of my reach, what I can do about it. I have only a vague assumption, that Moodle is more strict in the course context levels and above, and might not be as strict in the activity context level - but I have no proof.

Moodle has a own cache implementation so called MUC cache which is completely run under the hood of Moodle where we have no influence. I assume the different categories of those caches in "Site administration -> Plugins -> Caching -> Configuration". There is one category called "capabilities". We have not enough data to prove or deny that idea, but we assume that only purging the "capabilities" cache there resolves the issue.

But whatever the reason might be, we seem to have to influence over that cache at all :(

To proof that the caching is at fault: Make a screenshot of the **Permissions in the StudentQuiz** (can be accessed in the affected studentquiz via the gear icon) after filtering those capabilities by "question".

**Comment by rschrenk** [comment]
The issue with the cache was in our case as follows: We have multiple webnodes, that have an individual cache. So when a teacher makes role assignments, only the cache of the current webnode is touched, although the changes affect other users, that may be connected to other webnodes. Logically, erasing all caches on all webnodes solve the problem.

So if the capabilities are checked once a student enters the studentquiz, and are granted when missing, this would be no problem at all anymore.

**Comment by dionysius** [comment]
It's the responsibility of the system to keep the settings in sync over all nodes. And if that system has a cache, it must do that as well. We can't do anything here with StudentQuiz, your proposal is not the way StudentQuiz should interact with the system. Feel free to investigate into this issue to try to find the cause and raise an issue to Moodle's issue tracker. If you can describe your setup where this issue occurs reproducable, I'm sure they can investigate further. The tracking of this kind of issue is in #203
