### ISSUE TITLE
mod_studentquiz incredibly slowing down our site

### ISSUE THREAD

**Issue by rschrenk** [frankkoch/moodle-mod_studentquiz#306]
Hello,

we are using certain roles on the system and certain course category contexts. We experienced that processing role assignments and unassignments was getting slower and slower by the time. Recently we ran into timeout errors and made a deeper analysis what was going on.

In this example, one user is assigned 1 role and unassigned one role at the same time.

We found out, that the observer of mod_studentquiz is called every time, when a role changes. As you can see, it consumes extremely much of the time for mapping the roles to override capabilities.

![mod_studentquiz](https://user-images.githubusercontent.com/8080807/105686988-34764a80-5ef8-11eb-8518-f869010911f1.png)

I am not sure what the purpose is to check for role assignments above the course context. IMHO mod_studentquiz only needs to consider course enrolments and course roles.

Could you please consider to (1) introduce a new role that grants the required capabilities and is assigned to all users automatically on the level of the course module based on course enrolments, and (2) use ad hoc tasks so that these assignments (that are not time critical) are performed by the cronjob?

Kind regards

**Comment by rschrenk** [comment]
Here is the overview of the cards - all huge blocks are due to mod_studentquiz.

![mod_studentquiz-blocks](https://user-images.githubusercontent.com/8080807/105687518-d72ec900-5ef8-11eb-93eb-531ac7130d0c.png)

**Comment by rschrenk** [comment]
Hello,

a colleague of mine had another idea, how this could be more efficient. Her idea was as follows:

"Perhaps, instead of mapping all capabilities once a role is assigned or unassigned, you could do the mapping when a user enters the studentquiz. At this time Moodle has all capabilities of this user in the particular studentquiz instance already in cache. You just need to consider, if access to questionbank is possible, and if not, map it instantly."

Kind regards

**Comment by dionysius** [comment]
Thanks for your issue, it is also in our interest to not require more resources than required. This change had been introduced (and more info can be found there) in #270 and the followup #271. We have to update the overrides instantly, as the changes an admin/teacher does to the enrolments/roles/capabilities are immediately required for the students, otherwise they run into missing_capabilities issue like you posted in #304.

We tried to exit as early as we could, e.g. in the capability related events, we could check for the specific studentquiz capabilities: https://github.com/frankkoch/moodle-mod_studentquiz/blob/33add3d0f5fb8563916709da5faab9573376bc8c/classes/observer.php#L177

You are right, as for the roles related events there is indeed no early exit check. Let me see if we can achieve that, I'll have to look what the event object has to offer. The problem why role changes have to be considered is described in #270. We have to detect the first time a user with a new role is enrolled in the course and when a role is not used by any user anymore.

The improvement could consider that it really only applies the capability overrides the first time a role gets introduced, and when the role gets removed from the course. The difficult part might be to detect that without a lot of ressources.

**Comment by rschrenk** [comment]
Thanks for your fast reply.
At least it would help if you could do that using ad hoc tasks. They should run very soon after a role has changed, but do not freeze the user session.
Greetz

**Comment by lucaboesch** [comment]
Robert, did you manage to comment out some line in StudentQuiz to proof the load on your system got better?
Best,
Luca

**Comment by rschrenk** [comment]
I inserted a "return;" at the beginning of the function, that caused the issue. I am not sure now, which it was.

Is there a particular reason why students need the capabilities even before they access the studentquiz?

**Comment by dionysius** [comment]
> Is there a particular reason why students need the capabilities even before they access the studentquiz?

Yes.

Note on @lucaboesch's answer https://github.com/frankkoch/moodle-mod_studentquiz/issues/306#issuecomment-766888721, you need to purge the cache for the changes to take effect.

But we better solve the issue than working around it.

Can you give us the lower part of the image in your initial comment https://github.com/frankkoch/moodle-mod_studentquiz/issues/306#issue-793206895?

**Comment by rschrenk** [comment]
I think that the cache-problem would be better met, if the capability is checked once a student enters the quiz.

If, for any reason, the cache is not up to date, it will try to assign the capability. If it is already there, the database will not be changed, but the cache will be.

Here is the lower part of the image:
![mod_studentquiz](https://user-images.githubusercontent.com/8080807/105749596-ebe47e80-5f43-11eb-8ee1-e76a09b924fb.png)

**Comment by dionysius** [comment]
Hmm... I don't know how to properly interpret that diagram, so I can't come to a definitive conclusion. I assume that this is a statistic over some period of time. Very unusual is that there happens **more unassigned** events than assigned. Are you using some additional script or module to (automatically) manage enrolments/roles of users? If so, it seems to me, that it tries to unassign roles everything first and then assigns roles again - instead of acting on the case by case basis. But that doesn't mean that StudentQuiz can also do it's part to solve the issue.

> I think that the cache-problem would be better met, if the capability is checked once a student enters the quiz.

The checking part *is* done when student enters a page accordingly. Lets leave the caching out of this issue, as this is not related for now. My comment about purge caches was related to the actions, if someone changes the available actions and events, moodle will only reread that file of a module when the caches are purged.

So, what we can do here is trying limit the execution of `mod_studentquiz_observer::apply_capability_override` to when it only matters.
- A role is added to a user, either in the course enrolments - thus course context - or on a higher level (e.g. system context)
- Then distinguish between those context to narrow down affected courses
- If that course has no studentquiz there is no need to go further
- If that role is already in that course, no need to go further
- All this must also ensure, that the removal of this role, when it was the last one, also removes those capability overrides

While `context_override::ensure_relation` already checks to only change when needed, it can probably be stopped at a earlier stage by those boundaries.

I also have nothing against the ad-hoc tasks, every useful feature should be used. They just must ensure that this task is run within the next 5 to 10 seconds (I made that up right now). Because <Insert any dialog use-case>: E.g. a teacher might give some permissions to the non-editing teacher (e.g. `mod_studentquiz::changestate`) and then tells him over the table, that he should now try again - which definitely should have happened within 5-10 seconds.

We're open for any implementation proposals

**Comment by rschrenk** [comment]
I investigated this issue a little and found that, the following events occur:
![events](https://user-images.githubusercontent.com/8080807/105842159-0a935580-5fd6-11eb-816b-b25802c105c5.png)

In case the role was assigned on system level, the courseid is zero. I assume this is also the case for role assignments in course categories.

The event observer of yours just takes the courseid from the event and calls `apply_capability_override()`

This function loads all studentquiz-modules from the database. If the courseid is zero, it will actually load **all** of them. If courseid is empty, the params-array will be empty.

```
        $params = array();
        if (!empty($courseid)) {
            $params['course'] = $courseid;
        }

        $studentquizes = $DB->get_records('studentquiz', $params);
```

As a matter of fact you loop through all studentquizes of the whole site and override the capabilities.

From my point of view, there are two possibilities:

1. Ignore the event, if the courseid is zero.
2. Instead of using the courseid, use the contextid, in that case you could load from the contexts-Table all child-contexts of it, that have the contextlevel 50 (course level).

As a hotfix I chose 1 for our site.

`if (empty($courseid)) return;`

**Comment by rschrenk** [comment]
Just as info: Role assignment on system level now only takes milliseconds.

**Comment by dionysius** [comment]
Well, it's a viable setting from the admin/manager to allow setting of a studentquiz capability on system level, so he doesn't have to do it in every course. We can't remove that. As I wrote in my previous post, the only thing we can do, is to more efficiently find out, if there is a need for change after such an event.

**Comment by dionysius** [comment]
In case I was not clear, we need a better version of this function: capable of getting all the required info in **one optimized query**:
![105749596-ebe47e80-5f43-11eb-8ee1-e76a09b924fb](https://user-images.githubusercontent.com/1341084/105845175-a4f59800-5fda-11eb-9987-6ad9a69d6a95.png)
Documentation: https://wimski.org/api/3.8/da/d16/group__core__access.html
Source: https://github.com/moodle/moodle/blob/master/lib/accesslib.php#L2697

**Comment by dionysius** [comment]
But as I said before, have you considered looking into the source of the events? For example why there are so many changes.

**Comment by timhunt** [comment]
Not sure if I can say anything helpful here, but let me try.

The underlying issue is the within a studentquiz, we need certain core/question capabilities to be set in synch we certain mod/studentquiz capabilibies.

And any change to roles setup can get it out of synch. We have a function that you can call to fix things up for one studentquiz context.

There are two simple approaches that could be applied:

1. Call the fixup function every time a user accesses something in a studentquiz. _This would cause performance problems for users interactin with a studentquiz._

2. [What we currenty do] Call the fixup function, via an event hander, whenever roles are edited. _This causes performance problems when people are managing roles._

So, we need something a bit more sophisticated. The best logic would be:

3. Whenever a User does something in a studentquiz, call the fixup function if there has been a roles change since the last time we called fixup.

Probably the best-performing way to implement this is with a MUC cache. It could have one cache key 'last-role-change', and then all the roles event handlers just need to set that to the current time. Then for each StudentQuiz, have a cache key like 'fixup-called-for-cm-123'. Then have a funciton which can be called on every page in a StudentQuiz, which compares the two values, and calls the fixup function if necessary. The fixup function can set the second cache key.

**Comment by lucaboesch** [comment]
> if (empty($courseid)) return;

That could be
`if ($courseid == 0) return;
`
too, probably, couldn't it?

**Comment by rschrenk** [comment]
if $courseid really is 0 it would work. But if $courseid is an empty string, $courseid == 0 would return false, while empty($courseid) returns true. Therefore I would consider empty to be more accurate in our case.

**Comment by lucaboesch** [comment]
> if $courseid really is 0 it would work. But if $courseid is an empty string or false, $courseid == 0 would return false, while empty($courseid) returns true. Therefore I would consider empty() to be more accurate in our case.

Let's meet each other halfway then :-)

`if (($courseid == 0) || (empty($courseid))) return;`

**Comment by dionysius** [comment]
This is not true, php makes a very weak comparison and can compare different data types with `==`, only `===` requires type checking: https://www.tehplayground.com/cHYhIsxTOjIJQzWd

**Comment by timhunt** [comment]
It seems that we are hitting this too - and not when users edit roles, but when we upgraded to the latest studentquiz on our main database, the call to context_override::ensure_relation took about 20 minutes.

I guess I will be looking into this.

**Comment by timhunt** [comment]
So, that is my propsed fix for this. It turned out to be less complicated that I feared it might be. Does anyone have time to take a look at the code?

**Comment by timhunt** [comment]
Currently, there are 3 failing Behat tests, which I will look at this afternoon. Would still be helpful to have any review comments.

**Comment by timhunt** [comment]
So, all the Behat failures were spurious. When I re-ran them. they all passed. So, I will send a pull request.

**Comment by timhunt** [comment]
I have now deployed my fix to our test environment, and sone some profiling.

Before, a role-assign (or edit role and change StudentQuiz capability) in system context too about 13 seconds (we have ~50 roles and ~25 student quizzes)

After, all role chagnes are instant (At most a few ms in the profiling from StudentQuiz).

Then, when a user first goes to a StudentQuiz activity, after a roles chnage has been amde, or caches purged, that adds 0.7s if some permission changes need to be made, or 0.3s if it just need to check and verify that no changes are requierd. (And for sites with a more sensible number of roles, rather than our crazy 50, it will be even quicker.)

So, I think this is a good change. It still needs more testing to verify that there are not subtle permissions bugs which are not detected by the PHPunit and Behat tests.

**Comment by timhunt** [comment]
I just rebased the branch to add in the missing lang string (cache name).
