### ISSUE TITLE
unexpected errors occurs when attempting to enter calculated questions/calculated multichoice/calculated simple type questions

### ISSUE THREAD

**Issue by Fae6068123** [frankkoch/moodle-mod_studentquiz#307]
Users are given an error which is hardcoded into the code to always appear when users enter a question. 
"There should be at least one wild card in answer formula or question text"
to reproduce, create a question, as shown below 
![image](https://user-images.githubusercontent.com/59917516/107230595-2dcaf580-6a17-11eb-9f99-53d62b4f4b7c.png)
enter details of question
![image](https://user-images.githubusercontent.com/59917516/107230812-6d91dd00-6a17-11eb-885b-aee67875769d.png)
the error message appears...
![image](https://user-images.githubusercontent.com/59917516/107230891-85696100-6a17-11eb-8426-4eea8bff163f.png)

**Comment by Fae6068123** [comment]
this is a known bug and is caused by a hardcoded error message which is set to appear no matter what users enter. as a result, the application cannot be used until the error is removed.

**Comment by dionysius** [comment]
How do you mean "application cannot be used until the error is removed"?

**Comment by dionysius** [comment]
You might have encountered: https://github.com/frankkoch/moodle-mod_studentquiz/issues/269

**Comment by Fae6068123** [comment]
It will not save at all. only way round is to change question type. Calculated questions have this bug. when attempting to enter anything, when clicking on preview users get following error message 
![image](https://user-images.githubusercontent.com/59917516/107344606-8d2e1180-6aba-11eb-9891-58e3733a5fa1.png)

**Comment by Fae6068123** [comment]
unfortunately, documentation is very poor and confusing so users have no idea how to create calculated questions

**Comment by dionysius** [comment]
As stated in #269 and I highly think you encountered this: This question type weirdly requires the capabilty [question:movemine](https://docs.moodle.org/39/en/Capabilities/moodle/question:movemine) which we **do not** want to give students by default, as this allows students to move questions away from that studentquiz to other studentquizzes. You can add this permission to your students **at your own risk** on course level or higher (read the documentation about this capabilty).

The bug is in Moodle itself [MDL-69872](https://tracker.moodle.org/projects/MDL/issues/MDL-69872) and unless this is something else I'm closing this issue. There is nothing we can do in StudentQuiz except give you this workaround with that provided warning.
