### ISSUE TITLE
Users unable to export to Aitken format 

### ISSUE THREAD

**Issue by Fae6068123** [frankkoch/moodle-mod_studentquiz#308]
Users when attempting to export questions to Aitken or Gift format are given following error message
![image](https://user-images.githubusercontent.com/59917516/107347799-1c88f400-6abe-11eb-8660-c564d77ead37.png)

to reproduce: click on export, choose aitken or gift format:
![image](https://user-images.githubusercontent.com/59917516/107347881-3591a500-6abe-11eb-89d5-142205d654e4.png)
![image](https://user-images.githubusercontent.com/59917516/107348052-6ffb4200-6abe-11eb-896f-05d4e0e0f9ad.png)

**Comment by dionysius** [comment]
Confirm, on my local moodle 39 development installation this happens as well. The main question bank functionality including import/export is pure Moodle code, just used in the activity context. This confirms that this is a moodle bug: This exact issue happens as well in the quiz module! I've added there questions to the activity context and tried to export it.

Please raise a bug in the [moodle tracker](https://tracker.moodle.org). There's nothing we can do about it unless fixed in moodle.
