### ISSUE TITLE
Next and Finish buttons missing for Description and Essay type questions.

### ISSUE THREAD

**Issue by jebarviabb** [frankkoch/moodle-mod_studentquiz#66]
If there is a Description or Essay type question in the studentquiz (preferably in the middle part of the quiz), and it gets loaded/previewed, there is no Next or Finish buttons to navigate onto the next question of the quiz.

1. Create a course.
2. Turn editing on and add a studentquiz activity.
3. Click on "Add a question" 
4. Choose "description" 
5. Add anything in the "question name" and "question text" fields 
6. Save the question 
7. Attempt the quiz with the description question selected 
8. When the quiz displays the description question, notice an absence of "next" and "finish" buttons

**Comment by muqiuq** [comment]
The essay question doesn't make any sense in studentquiz because it has to be evaluated manually. This is against the studentquiz idea of beeing evaluated without human interaction. After this commit the essay question can not be added anymore. If for some reason it is displayed it is shown readonly. The description question type now showes "Next" button.
